package com.yolaine.client.ui.clients.client.event;


public enum ClientEventPropertyName {    
    
    IDENTIFIANT_CHANGED,
    CIVILITE_CHANGED,
    NOM_CHANGED,
    PRENOM_CHANGED,
    DEPOSANT_CHANGED,
    LOGIN_CHANGED,
    PASSWORD_CHANGED,
    TELEPHONE_FIXE_CHANGED,
    TELEPHONE_PORTABLE_CHANGED,
    EMAIL_CHANGED,
    TYPEIDENTITE_CHANGED,
    NUMEROIDENTITE_CHANGED,
    DATE_DE_NAISSANCE_CHANGED,  
    COMMENTAIRE_CHANGED,
    CHAMP_NUMERIQUE_1_CHANGED,
    CHAMP_NUMERIQUE_2_CHANGED   
}