ALTER TABLE t_categorie_marque DROP CONSTRAINT categorie_marque_fk;
ALTER TABLE t_categorie_marque DROP CONSTRAINT categorie_fk_marque;
ALTER TABLE t_remboursement DROP CONSTRAINT remboursement_type_fk;
ALTER TABLE t_remboursement DROP CONSTRAINT remboursement_banque_fk;
ALTER TABLE t_paiement DROP CONSTRAINT paiement_type_fk;
ALTER TABLE t_paiement DROP CONSTRAINT paiement_banque_fk;
ALTER TABLE t_paiement DROP CONSTRAINT paiement_type_identite_fk;
ALTER TABLE t_client DROP CONSTRAINT client_civilite_fk;
ALTER TABLE t_client DROP CONSTRAINT client_adresse_fk;
ALTER TABLE t_client DROP CONSTRAINT client_type_identite_fk;
ALTER TABLE t_article DROP CONSTRAINT article_depot_fk;
ALTER TABLE t_article DROP CONSTRAINT article_client_fk;
ALTER TABLE t_article DROP CONSTRAINT article_categorie_fk;
ALTER TABLE t_article DROP CONSTRAINT article_marque_fk;
ALTER TABLE t_article DROP CONSTRAINT article_couleur_1_fk;
ALTER TABLE t_article DROP CONSTRAINT article_couleur_2_fk;
ALTER TABLE t_article DROP CONSTRAINT article_manche_fk;
ALTER TABLE t_article DROP CONSTRAINT article_situation_fk;
ALTER TABLE t_article DROP CONSTRAINT article_paiement_fk;
ALTER TABLE t_article DROP CONSTRAINT article_remboursement_fk;
ALTER TABLE t_depot DROP CONSTRAINT depot_client_fk;

DROP TABLE t_categorie_marque;
DROP TABLE t_civilite;
DROP TABLE t_situation;
DROP TABLE t_banque;
DROP TABLE t_type_identite;
DROP TABLE t_type_paiement;
DROP TABLE t_marque;
DROP TABLE t_categorie;
DROP TABLE t_couleur;
DROP TABLE t_manche;
DROP TABLE t_remboursement;
DROP TABLE t_paiement;
DROP TABLE t_adresse;
DROP TABLE t_client;
DROP TABLE t_article;
DROP TABLE t_depot;
